/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios07;

import javax.swing.JOptionPane;

/**
 *
 * @author Larissa Souza
 */
public class ExercicioUm extends javax.swing.JFrame {

    /**
     * Creates new form ExercicioUm
     */
    public ExercicioUm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblProdutos = new javax.swing.JLabel();
        tglCoca = new javax.swing.JToggleButton();
        tglSabao = new javax.swing.JToggleButton();
        tglBombril = new javax.swing.JToggleButton();
        tglSkol = new javax.swing.JToggleButton();
        btnOk = new javax.swing.JButton();
        lblCoca = new javax.swing.JLabel();
        lblSabao = new javax.swing.JLabel();
        lblBombril = new javax.swing.JLabel();
        lblSkol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProdutos.setText("PRODUTOS");

        buttonGroup1.add(tglCoca);
        tglCoca.setText("Coca Cola");

        buttonGroup1.add(tglSabao);
        tglSabao.setText("Sabao Omo");

        buttonGroup1.add(tglBombril);
        tglBombril.setText("Bombril");

        buttonGroup1.add(tglSkol);
        tglSkol.setText("Skol");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblCoca.setText("7,00");

        lblSabao.setText("6,50");

        lblBombril.setText("2,30");

        lblSkol.setText("6,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tglCoca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCoca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tglSabao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSkol)
                            .addComponent(lblSabao)
                            .addComponent(lblBombril))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOk)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tglBombril))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(lblProdutos))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tglSkol))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblProdutos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglCoca)
                    .addComponent(lblCoca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSabao)
                    .addComponent(lblSabao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglBombril)
                    .addComponent(lblBombril))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSkol)
                    .addComponent(lblSkol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
       boolean opcaoCoca = tglCoca.isSelected();
        boolean opcaoSabao = tglSabao.isSelected();
        boolean opcaoBombril = tglBombril.isSelected();
        boolean opcaoSkol = tglSkol.isSelected();
        
        
        if (opcaoCoca == true) {
            JOptionPane.showMessageDialog(null, "O produto é Coca Cola"
                    + "\nValor: 7.00 "
                    );
        }
        else if (opcaoSabao == true){
           JOptionPane.showMessageDialog(null, "O produto é Sabao "
                   + "\nValor: 6.50  " 
                    ); 
            
        }
        else if (opcaoBombril = true) {
            JOptionPane.showMessageDialog(null, "O produto é Bombril "
                    + "\nValor: 2.30"
                  );
        }
        else {
            JOptionPane.showMessageDialog(null, "O produto é Skol "
                    + "\nValor: 6.00 " );
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioUm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblBombril;
    private javax.swing.JLabel lblCoca;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblSabao;
    private javax.swing.JLabel lblSkol;
    private javax.swing.JToggleButton tglBombril;
    private javax.swing.JToggleButton tglCoca;
    private javax.swing.JToggleButton tglSabao;
    private javax.swing.JToggleButton tglSkol;
    // End of variables declaration//GEN-END:variables
}
