/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios07;

import javax.swing.JOptionPane;

/**
 *
 * @author Larissa Souza
 */
public class ExercicioDois extends javax.swing.JFrame {

    /**
     * Creates new form ExercicioDois
     */
    public ExercicioDois() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglCoca = new javax.swing.JToggleButton();
        tglSabao = new javax.swing.JToggleButton();
        tglBombril = new javax.swing.JToggleButton();
        tglSkol = new javax.swing.JToggleButton();
        lblProdutod = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblCoca = new javax.swing.JLabel();
        lblSabao = new javax.swing.JLabel();
        lblBombril = new javax.swing.JLabel();
        lblSkol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tglCoca.setText("Coca Cola");

        tglSabao.setText("Sabao Omo");

        tglBombril.setText("Bombril");

        tglSkol.setText("Skol");
        tglSkol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSkolActionPerformed(evt);
            }
        });

        lblProdutod.setText("PRODUTOS");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblCoca.setText("7,00");

        lblSabao.setText("6,50");

        lblBombril.setText("2,30");

        lblSkol.setText("6,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tglSkol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSkol))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tglBombril)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBombril))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tglSabao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSabao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tglCoca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCoca)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProdutod)
                    .addComponent(btnOk))
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProdutod)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglCoca)
                    .addComponent(lblCoca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSabao)
                    .addComponent(lblSabao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglBombril)
                    .addComponent(lblBombril))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSkol)
                    .addComponent(lblSkol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglSkolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSkolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglSkolActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        double valorCoca = 0;
        double valorSabao = 0;
        double valorBombril = 0;
        double valorSkol = 0;
        double tudo;
        
        boolean opcaoCoca = tglCoca.isSelected();
        boolean opcaoSabao = tglSabao.isSelected();
        boolean opcaoBombril = tglBombril.isSelected();
        boolean opcaoSkol = tglSkol.isSelected();
        
        
        if (opcaoCoca == true) {
            JOptionPane.showMessageDialog(null, "O produto é Coca Cola R$: 7.00"          
                    ); 
            valorCoca = 7.00;
        }
        if (opcaoSabao == true){
           JOptionPane.showMessageDialog(null, "O produto é Sabao R$: 6.50 "
                    ); 
            valorSabao = 6.50;
        }
        if (opcaoBombril == true) {
            JOptionPane.showMessageDialog(null, "O produto é Bombril R$ 2.30 "
                  );
            valorBombril = 2.30;
        }
        else {
            JOptionPane.showMessageDialog(null, "O produto é Skol R$ 6.00 "
                 );
            valorSkol = 6.00;
        }
        
        tudo = valorCoca + valorSabao + valorSkol + valorBombril;
        
        JOptionPane.showMessageDialog(null, "Total:" + tudo);
        
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioDois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblBombril;
    private javax.swing.JLabel lblCoca;
    private javax.swing.JLabel lblProdutod;
    private javax.swing.JLabel lblSabao;
    private javax.swing.JLabel lblSkol;
    private javax.swing.JToggleButton tglBombril;
    private javax.swing.JToggleButton tglCoca;
    private javax.swing.JToggleButton tglSabao;
    private javax.swing.JToggleButton tglSkol;
    // End of variables declaration//GEN-END:variables
}
